FROM mcr.microsoft.com/dotnet/sdk:7.0
LABEL author="srikanthvelma" org="qt" project="docker"
ADD https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.2/nopCommerce_4.60.2_NoSource_linux_x64.zip /nop/nopCommerce_4.60.2_NoSource_linux_x64.zip
ENV ASPNET_URLS=http://0.0.0.0:5000
WORKDIR /nop
RUN apt update && \
apt install unzip -y && \
unzip /nop/nopCommerce_4.60.2_NoSource_linux_x64.zip && \
mkdir /nop/bin && mkdir /nop/logs
EXPOSE 5000
CMD [ "dotnet", "Nop.Web.dll"]
